version: '3.8'

services:
  app:
    build: .
    container_name: autoria-scraper
    env_file:
      - .env
    volumes:
      - ./dumps:/app/dumps
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - autoria-network

  db:
    image: postgres:15
    container_name: autoria-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: unless-stopped
    networks:
      - autoria-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  autoria-network:
    driver: bridge

volumes:
  postgres_data: